version: '2'
services:
    test-server:
        image: clue/json-server
        volumes:
            - ./server/db.json:/data/db.json:ro

    runner:
        image: graze/cucumber-rest-bdd
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/opt/src
        working_dir: /opt/src
        environment:
            - endpoint=http://test-server/
            - cucumber_api_verbose=false
            - field_separator=_
            - field_camel=true
            - resource_single=false
            - data_key=
